"""add is_initial_field to tariff model

Revision ID: 9306b3f88e7b
Revises: 7ed5d09eda72
Create Date: 2026-02-20 19:40:38.382903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9306b3f88e7b'
down_revision: Union[str, Sequence[str], None] = '7ed5d09eda72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('is_initial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'is_initial')
    # ### end Alembic commands ###
